/**
 * Netlify Function: /api/report
 * Generates a plain-text PDF feasibility report.
 * JavaScript rewrite of report.py
 */

function corsHeaders() {
  return {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
  }
}

exports.handler = async (event) => {
  if (event.httpMethod === 'OPTIONS') return { statusCode: 204, headers: corsHeaders(), body: '' }

  try {
    const body = JSON.parse(event.body || '{}')

    // Build a simple text-based report (no PDF library needed for hackathon demo)
    // Return as plain text — frontend can display or save
    const address = body.address || 'Unknown parcel'
    const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

    const text = `
SITESENSE FEASIBILITY REPORT
Generated: ${now}
Address: ${address}
================================================================

This report was generated by SiteSense AI Land Feasibility Tool.
For the full interactive report, visit the SiteSense dashboard.

⚠️ DISCLAIMER: This report is for preliminary planning purposes only.
It is not a substitute for a licensed Professional Engineer (PE) review.
All engineering decisions must be verified by a qualified engineer
before any construction activity.

================================================================
SiteSense | HackASU 2025 | Mobasher Group, ASU
`.trim()

    const base64 = Buffer.from(text, 'utf-8').toString('base64')

    return {
      statusCode: 200,
      headers: { ...corsHeaders(), 'Content-Type': 'text/plain', 'Content-Disposition': 'attachment; filename="SiteSense_Report.txt"' },
      body: text,
    }
  } catch (e) {
    return { statusCode: 500, headers: corsHeaders(), body: JSON.stringify({ status: 'error', message: e.message }) }
  }
}
