/**
 * FloorPlanView — renders a 2D floor plan SVG + interactive 3D box model
 * from the room program generated by House Concept Estimator.
 */

import { useState, useRef, useCallback, useEffect } from 'react'

// Room colors by type
const ROOM_COLORS = {
  'Living Room':  { fill: '#1a4d5e', stroke: '#2dd4bf', label: '#5eead4' },
  'Kitchen':      { fill: '#4d3a1a', stroke: '#fbbf24', label: '#fcd34d' },
  'Dining':       { fill: '#3d1a4d', stroke: '#c084fc', label: '#d8b4fe' },
  'Primary Bedroom': { fill: '#1a2e4d', stroke: '#60a5fa', label: '#93c5fd' },
  'Bedroom':      { fill: '#1a3d4d', stroke: '#67e8f9', label: '#a5f3fc' },
  'Primary Bath': { fill: '#1a4d3a', stroke: '#34d399', label: '#6ee7b7' },
  'Bath':         { fill: '#1a4d3a', stroke: '#34d399', label: '#6ee7b7' },
  'Stairway':     { fill: '#3d3d1a', stroke: '#a3a310', label: '#d4d42a' },
  'Laundry':      { fill: '#4d2e1a', stroke: '#fb923c', label: '#fdba74' },
  'Hallway':      { fill: '#2a2a2a', stroke: '#6b7280', label: '#9ca3af' },
  'default':      { fill: '#1e293b', stroke: '#94a3b8', label: '#cbd5e1' },
}

function getRoomColor(name) {
  if (name.startsWith('Bedroom')) return ROOM_COLORS['Bedroom']
  if (name.startsWith('Bath')) return ROOM_COLORS['Bath']
  return ROOM_COLORS[name] || ROOM_COLORS['default']
}

// Pack rooms into a rectangular floor layout using a simple strip-packing algorithm
function packRooms(rooms, footprintSF, stories) {
  if (!rooms || rooms.length === 0) return { rects: [], width: 0, height: 0 }

  // Determine footprint dimensions (roughly 1.2:1 aspect ratio)
  const aspect = 1.3
  const footW = Math.sqrt(footprintSF * aspect)
  const footH = footprintSF / footW

  // Group rooms by floor
  const floors = {}
  rooms.forEach(r => {
    const f = r.floor || 1
    if (!floors[f]) floors[f] = []
    floors[f].push(r)
  })

  const rects = []

  for (const [floorNum, floorRooms] of Object.entries(floors)) {
    // Sort: largest rooms first for better packing
    const sorted = [...floorRooms].sort((a, b) => (b.targetSF || 0) - (a.targetSF || 0))
    const floorArea = sorted.reduce((s, r) => s + (r.targetSF || 100), 0)

    // Simple row-based packing
    let curX = 0, curY = 0, rowH = 0
    const floorW = footW
    const scale = Math.sqrt(floorArea / (footW * footH)) // normalize

    for (const room of sorted) {
      const area = room.targetSF || 100
      // Make room roughly square-ish
      const roomW = Math.sqrt(area * 1.2)
      const roomH = area / roomW

      // Wrap to next row if exceeds floor width
      if (curX + roomW > floorW + 1) {
        curX = 0
        curY += rowH + 1
        rowH = 0
      }

      rects.push({
        name: room.name,
        floor: parseInt(floorNum),
        x: curX,
        y: curY,
        w: roomW,
        h: roomH,
        sf: Math.round(area),
        color: getRoomColor(room.name),
      })

      curX += roomW + 1
      rowH = Math.max(rowH, roomH)
    }
  }

  // Compute bounds
  const maxX = Math.max(...rects.map(r => r.x + r.w))
  const maxY = Math.max(...rects.map(r => r.y + r.h))

  return { rects, width: maxX, height: maxY }
}

// ── 2D Floor Plan SVG ───────────────────────────────────────────────────────
function FloorPlan2D({ layout }) {
  const rooms = layout?.rooms || []
  const footprintSF = layout?.footprintSF || layout?.totalSF || 1200
  const stories = layout?.stories || 1

  const { rects, width, height } = packRooms(rooms, footprintSF, stories)
  if (rects.length === 0) return null

  const padding = 8
  const svgW = width + padding * 2
  const svgH = height + padding * 2

  // Group by floor
  const floorNums = [...new Set(rects.map(r => r.floor))].sort()

  return (
    <div>
      <div className={`grid gap-3 ${floorNums.length > 1 ? 'grid-cols-2' : 'grid-cols-1'}`}>
        {floorNums.map(fn => {
          const floorRects = rects.filter(r => r.floor === fn)
          const fMaxX = Math.max(...floorRects.map(r => r.x + r.w))
          const fMaxY = Math.max(...floorRects.map(r => r.y + r.h))
          const fW = fMaxX + padding * 2
          const fH = fMaxY + padding * 2

          return (
            <div key={fn} className="bg-gray-800/50 rounded-lg p-2">
              <p className="text-xs text-gray-400 mb-1 text-center font-semibold">Floor {fn}</p>
              <svg viewBox={`0 0 ${fW} ${fH}`} className="w-full" style={{ maxHeight: 280 }}>
                {/* Outer wall */}
                <rect x={padding/2} y={padding/2} width={fMaxX + padding} height={fMaxY + padding}
                  fill="none" stroke="#475569" strokeWidth="0.8" strokeDasharray="3,2" />

                {floorRects.map((r, i) => (
                  <g key={i}>
                    <rect
                      x={r.x + padding} y={r.y + padding}
                      width={r.w} height={r.h}
                      fill={r.color.fill} stroke={r.color.stroke}
                      strokeWidth="0.6" rx="1"
                    />
                    {/* Room name */}
                    <text
                      x={r.x + padding + r.w / 2}
                      y={r.y + padding + r.h / 2 - 2}
                      textAnchor="middle" dominantBaseline="middle"
                      fill={r.color.label} fontSize={Math.min(r.w / 6, 4)} fontWeight="600"
                    >
                      {r.name.replace('Primary ', 'P. ').replace('Hallway / Circulation', 'Hall')}
                    </text>
                    {/* Area */}
                    <text
                      x={r.x + padding + r.w / 2}
                      y={r.y + padding + r.h / 2 + 4}
                      textAnchor="middle" dominantBaseline="middle"
                      fill={r.color.label} fontSize={Math.min(r.w / 7, 3)} opacity="0.7"
                    >
                      {r.sf} sf
                    </text>
                  </g>
                ))}
              </svg>
            </div>
          )
        })}
      </div>
    </div>
  )
}

// ── 3D Box Model (Canvas) ───────────────────────────────────────────────────
function FloorPlan3D({ layout }) {
  const canvasRef = useRef(null)
  const [rotation, setRotation] = useState({ x: 30, y: -35 })
  const dragRef = useRef({ active: false, lastX: 0, lastY: 0 })

  const rooms = layout?.rooms || []
  const footprintSF = layout?.footprintSF || layout?.totalSF || 1200
  const stories = layout?.stories || 1
  const { rects, width, height } = packRooms(rooms, footprintSF, stories)

  const draw = useCallback(() => {
    const canvas = canvasRef.current
    if (!canvas || rects.length === 0) return
    const parent = canvas.parentElement
    const W = parent.clientWidth
    const H = Math.round(W * 0.55)
    const dpr = window.devicePixelRatio || 1
    canvas.width = W * dpr; canvas.height = H * dpr
    canvas.style.width = W + 'px'; canvas.style.height = H + 'px'
    const ctx = canvas.getContext('2d')
    ctx.scale(dpr, dpr)
    ctx.clearRect(0, 0, W, H)

    const cx = W / 2, cy = H / 2
    const scale = Math.min(W, H) * 0.25 / Math.max(width, height, 1)
    const floorH = 12 // extrusion height per floor

    const radX = rotation.x * Math.PI / 180
    const radY = rotation.y * Math.PI / 180
    const cosX = Math.cos(radX), sinX = Math.sin(radX)
    const cosY = Math.cos(radY), sinY = Math.sin(radY)

    function proj(x, y, z) {
      const rx = (x - width / 2) * cosY - (y - height / 2) * sinY
      const ry = ((x - width / 2) * sinY + (y - height / 2) * cosY) * cosX - z * sinX
      const rz = ((x - width / 2) * sinY + (y - height / 2) * cosY) * sinX + z * cosX
      return { x: cx + rx * scale, y: cy - ry * scale, z: rz }
    }

    // Build quads (top + front + side faces for each room box)
    const quads = []
    for (const r of rects) {
      const z0 = (r.floor - 1) * floorH
      const z1 = r.floor * floorH
      const x0 = r.x, x1 = r.x + r.w, y0 = r.y, y1 = r.y + r.h

      // Top face
      const tl = proj(x0, y0, z1), tr = proj(x1, y0, z1)
      const br = proj(x1, y1, z1), bl = proj(x0, y1, z1)
      quads.push({ pts: [tl, tr, br, bl], z: (tl.z + br.z) / 2, color: r.color.fill, stroke: r.color.stroke, name: r.name, type: 'top' })

      // Front face
      const ftl = proj(x0, y1, z1), ftr = proj(x1, y1, z1)
      const fbr = proj(x1, y1, z0), fbl = proj(x0, y1, z0)
      quads.push({ pts: [ftl, ftr, fbr, fbl], z: (ftl.z + fbr.z) / 2, color: r.color.fill, stroke: r.color.stroke, type: 'front' })

      // Right face
      const rtl = proj(x1, y0, z1), rtr = proj(x1, y1, z1)
      const rbr = proj(x1, y1, z0), rbl = proj(x1, y0, z0)
      quads.push({ pts: [rtl, rtr, rbr, rbl], z: (rtl.z + rbr.z) / 2, color: r.color.fill, stroke: r.color.stroke, type: 'side' })
    }

    // Painter's algorithm
    quads.sort((a, b) => a.z - b.z)

    for (const q of quads) {
      ctx.beginPath()
      ctx.moveTo(q.pts[0].x, q.pts[0].y)
      for (let i = 1; i < q.pts.length; i++) ctx.lineTo(q.pts[i].x, q.pts[i].y)
      ctx.closePath()

      // Darken front/side faces
      const brightness = q.type === 'top' ? 1.0 : q.type === 'front' ? 0.7 : 0.5
      ctx.fillStyle = q.color
      ctx.globalAlpha = brightness
      ctx.fill()
      ctx.globalAlpha = 1
      ctx.strokeStyle = q.stroke
      ctx.lineWidth = 0.5
      ctx.stroke()

      // Label on top faces
      if (q.type === 'top' && q.name) {
        const midX = q.pts.reduce((s, p) => s + p.x, 0) / 4
        const midY = q.pts.reduce((s, p) => s + p.y, 0) / 4
        ctx.fillStyle = '#fff'
        ctx.font = '9px sans-serif'
        ctx.textAlign = 'center'
        ctx.fillText(q.name.replace('Primary ', 'P.').replace('Hallway / Circulation', 'Hall'), midX, midY)
      }
    }

    // Hint
    ctx.fillStyle = 'rgba(156,163,175,0.4)'
    ctx.font = '9px sans-serif'
    ctx.textAlign = 'right'
    ctx.fillText('Drag to rotate', W - 8, H - 6)
  }, [rects, width, height, rotation])

  useEffect(() => { draw() }, [draw])

  const onMouseDown = e => { dragRef.current = { active: true, lastX: e.clientX, lastY: e.clientY } }
  const onMouseMove = e => {
    if (!dragRef.current.active) return
    setRotation(prev => ({
      x: Math.max(5, Math.min(85, prev.x + (e.clientY - dragRef.current.lastY) * 0.5)),
      y: prev.y + (e.clientX - dragRef.current.lastX) * 0.5,
    }))
    dragRef.current.lastX = e.clientX
    dragRef.current.lastY = e.clientY
  }
  const onMouseUp = () => { dragRef.current.active = false }

  if (rects.length === 0) return null

  return (
    <canvas ref={canvasRef}
      className="w-full rounded border border-gray-700 cursor-grab active:cursor-grabbing"
      style={{ background: '#0f172a' }}
      onMouseDown={onMouseDown} onMouseMove={onMouseMove}
      onMouseUp={onMouseUp} onMouseLeave={onMouseUp}
    />
  )
}

// ── Main Export ──────────────────────────────────────────────────────────────
export default function FloorPlanView({ layout }) {
  const [view, setView] = useState('2d')

  if (!layout?.rooms || !Array.isArray(layout.rooms) || layout.rooms.length === 0) return null

  return (
    <div className="bg-gray-800 rounded-lg p-4">
      <div className="flex items-center justify-between mb-2">
        <h3 className="text-xs font-semibold text-gray-400">Floor Plan — {layout.name}</h3>
        <div className="flex gap-1">
          <button onClick={() => setView('2d')}
            className={`text-xs px-2 py-0.5 rounded ${view === '2d' ? 'bg-teal-800 text-teal-200' : 'bg-gray-700 text-gray-400'}`}>
            2D Plan
          </button>
          <button onClick={() => setView('3d')}
            className={`text-xs px-2 py-0.5 rounded ${view === '3d' ? 'bg-teal-800 text-teal-200' : 'bg-gray-700 text-gray-400'}`}>
            3D Model
          </button>
        </div>
      </div>
      {view === '2d' && <FloorPlan2D layout={layout} />}
      {view === '3d' && <FloorPlan3D layout={layout} />}
    </div>
  )
}
